name: dependencies
on: pull_request  
jobs:
  changeset:
#     if: ${{ github.event.label.name == 'dependencies' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create/Update Changesets
        uses: 'the-guild-org/changesets-dependencies-action@main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
